service: openai-content-moderator

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    NODE_ENV: ${self:provider.stage}
    CORS_ORIGIN: ${env:CORS_ORIGIN, '*'}
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  timeout: 30
  memorySize: 512

functions:
  api:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-http
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3001